"""
skill_keywords.py — Shared Skill Keywords for SkillProof AI

Defines the master list of 48 technical and conceptual skill keywords
shared between the resume parser, job description parser, and matchmaking engine.
"""

from typing import List

SKILL_KEYWORDS: List[str] = [
    "C",
    "C++",
    "Java",
    "Python",
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "React",
    "Next.js",
    "Node.js",
    "Express.js",
    "Django",
    "Flask",
    "FastAPI",
    "REST API",
    "GraphQL",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Prisma",
    "Firebase",
    "Git",
    "GitHub",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "Linux",
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "NLP",
    "Computer Vision",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "Data Structures",
    "Algorithms",
    "OOP",
    "DBMS",
    "Operating System",
    "Computer Networks",
    "ETL",
    "Spark",
    "Airflow",
    "Data Pipeline",
    "Tailwind CSS",
    "Postman",
    "JWT",
]
